import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect } from "react";

const PrivacyPolicy = () => {
  useEffect(() => {
    document.title = "Privacy Policy - Dubai Real Estate";
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-6">
          <Link to="/">
            <Button variant="outline" className="mb-4">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </Button>
          </Link>
          <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
          <p className="text-muted-foreground">Last updated: January 2025</p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Introduction</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-gray max-w-none">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Interpretation and Definitions</CardTitle>
          </CardHeader>
          <CardContent>
            <h3 className="text-xl font-semibold mb-4">Interpretation</h3>
            <p className="mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
            
            <h3 className="text-xl font-semibold mb-4">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="space-y-2 list-disc list-inside">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Dubai Real Estate, Dubai, UAE.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: United Arab Emirates</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Collecting and Using Your Personal Data</CardTitle>
          </CardHeader>
          <CardContent>
            <h3 className="text-xl font-semibold mb-4">Types of Data Collected</h3>
            
            <h4 className="text-lg font-semibold mb-3">Personal Data</h4>
            <p className="mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="space-y-1 list-disc list-inside mb-6">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold mb-3">Usage Data</h4>
            <p className="mb-4">
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="mb-4">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. Data being handled exclusively by Bright Gate Properties, not shared with any unauthorized third parties.
            </p>
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Tracking Technologies and Cookies</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
            
            <h4 className="text-lg font-semibold mb-3">Cookie Types</h4>
            <div className="space-y-4">
              <div>
                <strong>Necessary / Essential Cookies</strong>
                <ul className="list-disc list-inside mt-2">
                  <li>Type: Session Cookies</li>
                  <li>Purpose: Essential to provide You with services available through the Website</li>
                </ul>
              </div>
              <div>
                <strong>Functionality Cookies</strong>
                <ul className="list-disc list-inside mt-2">
                  <li>Type: Persistent Cookies</li>
                  <li>Purpose: Remember choices You make when You use the Website</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Use of Your Personal Data</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="space-y-2 list-disc list-inside">
              <li>To provide and maintain our Service, including to monitor the usage of our Service</li>
              <li>To manage Your Account and registration as a user of the Service</li>
              <li>For the performance of a contract for products, items or services You have purchased</li>
              <li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication</li>
              <li>To provide You with news, special offers and general information about other goods and services</li>
              <li>To manage Your requests and attend to Your inquiries</li>
              <li>For business transfers, data analysis, and service improvement</li>
            </ul>
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Data Sharing</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="mb-4">We may share Your personal information in the following situations:</p>
            <ul className="space-y-2 list-disc list-inside">
              <li>With Service Providers to monitor and analyze the use of our Service</li>
              <li>For business transfers in connection with mergers, acquisitions, or asset sales</li>
              <li>With Affiliates, requiring them to honor this Privacy Policy</li>
              <li>With business partners to offer You certain products, services or promotions</li>
              <li>With Your consent for any other purpose</li>
            </ul>
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Data Security</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="mb-4">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Third-Party Services</CardTitle>
          </CardHeader>
          <CardContent>
            <h4 className="text-lg font-semibold mb-3">Mouseflow</h4>
            <p className="mb-4">
              Mouseflow is a session replay and heatmap tool that shows how visitors click, move, scroll, browse, and pay attention on websites. The service is operated by ApS.
            </p>
            <p>
              The information gathered by Mouseflow is held in accordance with its Privacy Policy: <a href="https://mouseflow.com/privacy/" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://mouseflow.com/privacy/</a>
            </p>
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Contact Information</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <ul className="space-y-1 list-disc list-inside">
              <li>By phone: +971 561700817</li>
              <li>By visiting our contact page</li>
              <li>By mail: Dubai, UAE</li>
            </ul>
          </CardContent>
        </Card>

        <Separator className="my-8" />
        
        <div className="text-center">
          <Link to="/">
            <Button size="lg">
              Return to Homepage
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;