// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuescfokmtibxzgeepux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZXNjZm9rbXRpYnh6Z2VlcHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTY2MDEsImV4cCI6MjA2OTM3MjYwMX0.CynpBdfdiNo__E_XLW49nRnd_fj0rnfVJxtxcDY0abg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});